% This is the list of
%   - channels to analyse that can be used
% If you want to introduce a nem denominatino add it here 
% ExpeInfo should only include elements from this nomenclature


%Electrode locations
locations_to_analyse = {'Ref',...
    'Bulb_sup','Bulb_deep',...
    'dHPC_sup','dHPC_deep','dHPC_rip',...
    'PaCx_sup','PaCx_deep', 'PFCx_sup',...
    'PFCx_deltasup','PFCx_deep','PFCx_deltadeep','PFCx_spindle', ...
    'MoCx_sup', 'MoCx_deep',...
    'AuCx',...
    'AuTh', 'NRT',...
    'Amyg',...
    'PiCx',...
    'InsCx',...
    'TaeniaTecta',...
    'EMG','EKG',...
    'VLPO',...
    'Respi'};
